Pundit
VinetiInternship2021/final-project-URS pull request #30
Opened 2021-05-22 19:29 UTC by TigranMS

2021-05-24 08:19 UTC, a-monemian-vineti requested changes

2021-05-24 08:19 UTC, a-monemian-vineti commented on Backend/app/models/user.rb
> +
why? :D

2021-05-24 08:19 UTC, a-monemian-vineti commented on Backend/app/models/user.rb
> -   enum role: ["admin","professor","student"]
I am surprised rubocop is not failing on this. there should be a space after each comma

2021-05-24 08:19 UTC, a-monemian-vineti commented on to the following files would be overwritten by checkout
> +
I guess this is a mistake, please remove the file

2021-05-24 18:01 UTC, Lusine0101 approved these changes

2021-05-26 07:02 UTC, a-monemian-vineti approved these changes

2021-05-26 07:06 UTC, merged